#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/calculator
#    username: root
#    password: Istanbul#9123
#  jpa:
#    hibernate:
#      ddl-auto: create
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect